version: '3'
services:
    website:
        build:
            context: .
        container_name: website
        image: zeek_website
        ports:
          - 9000:80
        stdin_open: true
        tty: true
