name: website_env

channels:
  - conda-forge
dependencies:
  - fastapi
  - joblib
  - uvicorn
  - loguru
  - numpy
  - requests
  - python-dotenv
  - aiofiles
  - python-multipart
  - jinja2
  - markdown
  - pytest
