# BUILDS AND RUNS DOCKER IMAGE
name: Build

on:
  push:
    branches:
      # any branch
      - '**'
    paths:
      # changes to files
      - '**.{html,css,py,yml,yaml}'
      - 'Dockerfile'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t zeek_website . --no-cache

    - name: Start Docker Service
      run: docker-compose up -d

    - name: Stop Docker Service
      run: docker-compose down

