name: Py Format
on: 
  push:
    branches:
      - '**'

jobs:
  src_changes:
    runs-on: 'ubuntu-20.04'
    # Declare outputs for next jobs
    outputs:
      src_changed: ${{ steps.check_file_changed.outputs.src_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh # the example this is adopted from makes use of PowerShell
      id: check_file_changed
      run: |
        # diff HEAD W/ previous commit
        $diff = git diff --name-only HEAD^ HEAD
        # check if specific folder with file extentions has changes
        $SourceDiff = $diff | Where-Object { $_ -match '.py$' }
        $HasDiff = $SourceDiff.Length -gt 0
        Write-Host "::set-output name=src_changed::$HasDiff"


  autopep8:
    needs: [ src_changes ]
    if: needs.src_changes.outputs.src_changed == 'True'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: autopep8
        uses: peter-evans/autopep8@v2
        with:
          args: --recursive --in-place --aggressive --aggressive .
    
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          #token: ${{ secrets.ZEEK_BOT_TOKEN }}
          author: zeek-bot <info@zeek.org>
          committer: zeek-bot <info@zeek.org>
          commit-message: autopep8 action changes
          title: PEP8 Format Fixes
          signoff: false
          body: This is an auto-generated PR with format fixes.
          labels: autopep8
          reviewers: akielaries
          branch: CICD_test


